peaker/Controllers/AthletesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using peaker.Models;
using peaker.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.WindowsAzure.Storage.Queue;
using Newtonsoft.Json;
using Microsoft.WindowsAzure.Storage;
using System.Configuration;
using peaker.Helpers;

namespace peaker.Controllers
{
    public class AthletesController : Controller
    {
        private PeakDbContext db = new PeakDbContext();

        // GET: Athletes
        public ActionResult Index()
        {
            // get logged in user
            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", null);
            }

            //get athlete
            var athlete = db.Athletes.FirstOrDefault(m => m.UserId == user.Id);

            if (athlete == null)
            {
                return View("Connect", null);
            }

            AthleteDetailViewModel ViewModel = new AthleteDetailViewModel();
            ViewModel.AthleteId = athlete.Id;
            ViewModel.AthleteName = athlete.Name;
            ViewModel.IndexedActivityCount = db.IndexedActivities.Where(m => m.Athlete.Id == athlete.Id).Count();
            ViewModel.AthleteSummitCompletions = db.SummitCompletions.Where(m => m.Athlete.Id == athlete.Id).Include(m => m.Peak).ToList();

            return View(ViewModel);
        }

        public JsonResult GetAthleteSummits(int? id)
        {
            if (id == null)
            {
                return Json("Id cannot be null", JsonRequestBehavior.AllowGet);
            }
            Athlete athlete = db.Athletes.Find(id);
            if (athlete == null)
            {
                return Json("Id not found", JsonRequestBehavior.AllowGet);
            }

            var summits = db.SummitCompletions.Where(m => m.Athlete.Id == athlete.Id).Include(m => m.Peak).ToList();

            return Json(summits, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ProccessActivities(int id)
        {
            QueueHelper.ProccessActivitiesForAthlete(id);

            return Json("proccessing", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

peaker/Controllers/PeaksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using peaker.Models;

namespace peaker.Controllers
{
    public class PeaksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Peaks
        public ActionResult Index()
        {
            return View(db.Peaks.ToList());
        }

        // GET: Peaks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peak peak = db.Peaks.Find(id);
            if (peak == null)
            {
                return HttpNotFound();
            }
            return View(peak);
        }

        // GET: Peaks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peaks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,STCTYFIPS,ELEV_METER,Latitude,Longitude")] Peak peak)
        {
            if (ModelState.IsValid)
            {
                db.Peaks.Add(peak);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(peak);
        }

        // GET: Peaks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peak peak = db.Peaks.Find(id);
            if (peak == null)
            {
                return HttpNotFound();
            }
            return View(peak);
        }

        // POST: Peaks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,STCTYFIPS,ELEV_METER,Latitude,Longitude")] Peak peak)
        {
            if (ModelState.IsValid)
            {
                db.Entry(peak).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(peak);
        }

        // GET: Peaks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Peak peak = db.Peaks.Find(id);
            if (peak == null)
            {
                return HttpNotFound();
            }
            return View(peak);
        }

        // POST: Peaks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Peak peak = db.Peaks.Find(id);
            db.Peaks.Remove(peak);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

peaker/Views/Athletes/Connect.cshtml
@model peaker.ViewModels.AthleteDetailViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>
</head>

<body>
    You are not connected to Strava

    <a href="https://www.strava.com/oauth/authorize?client_id=3764&response_type=code&redirect_uri=http://localhost:63041/strava/connect&approval_prompt=force"> Connect to Strava </a>

</body>
</html>

peaker/Views/Athletes/Create.cshtml
@model peaker.Models.Athlete

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Athlete</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

peaker/Views/Athletes/Delete.cshtml
@model peaker.Models.Athlete

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Athlete</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

peaker/Views/Athletes/Details.cshtml
@model peaker.ViewModels.AthleteDetailViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>

    @Styles.Render("~/Content/css")

    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />

    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>


    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            /*position: absolute;
            top: 0;
            bottom: 0;*/
            width: 100%;
            height: 500px;
        }
    </style>
</head>

<body>

    <p>Welcome, @Model.AthleteName</p>
    <p>We've indexed @Model.IndexedActivityCount activities</p>
    <p>You've summited @Model.AthleteSummitCompletions.Count() peaks!!</p>

    <div class="col-lg-5">
        <table class="table">
            <tr>
                <th>
                    Summit Completions
                </th>
                <th>
                    Height
                </th>
                <th>
                    Date
                </th>
                <th>
                    Strava
                </th>
            </tr>

            @foreach (var peak in Model.AthleteSummitCompletions)
            {
                <tr>
                    <td>
                        @peak.Peak.Name
                    </td>
                    <td>
                        @((int)(peak.Peak.ELEV_METER * 3.28084)) ft
                    </td>
                    <td>
                        date
                    </td>
                    <td>
                        <a href="http://strava.com/activities/@peak.StravaActivityId">Activity</a>
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="col-lg-7">
        <div id='map'></div>
    </div>

    <script>

        L.mapbox.accessToken = 'pk.eyJ1IjoiZ2tyYXRod29obCIsImEiOiJ5bXlHNXJJIn0.gjNMPWKFNso_Z5EmEjsFGA';
        var map = L.mapbox.map('map', 'mapbox.streets')
            .setView([40, -74.50], 9);

        $(document).ready(function () {
            var actionUrl = '@Url.Action("GetAthleteSummits", "Athletes", new { id=8 })';
            $.getJSON(actionUrl, displayData);
        });

        function displayData(response) {
            if (response != null) {
                console.log(response);
            }

            $.each(response, function (i, summit) {
                console.log(summit.Peak.Latitude);
                L.marker([summit.Peak.Latitude, summit.Peak.Longitude]).addTo(map);
            });
        }

    </script>

</body>
</html>

peaker/Views/Athletes/Edit.cshtml
@model peaker.Models.Athlete

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Athlete</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

peaker/Views/Athletes/Index.cshtml
@model peaker.ViewModels.AthleteDetailViewModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>

<head>

    @Styles.Render("~/Content/css")

    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />

    @*<link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>*@

    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.css' rel='stylesheet' />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>


    <style>
        body {
            margin: 0;
            padding: 0;
        }

        #map {
            /*position: absolute;
            top: 0;
            bottom: 0;*/
            width: 100%;
            height: 500px;
        }

        .mapboxgl-popup {
            max-width: 400px;
            font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
        }

        .marker-title {
            font-weight: 700;
        }

    </style>
</head>

<body>

    <p>Welcome, @Model.AthleteName</p>
    <p>We've indexed @Model.IndexedActivityCount activities</p>
    <p>You've summited @Model.AthleteSummitCompletions.Count() peaks!!</p>

    <div class="col-lg-5">
        <table class="table">
            <tr>
                <th>
                    Summit Completions
                </th>
                <th>
                    Height
                </th>
                <th>
                    Date
                </th>
                <th>
                    Strava
                </th>
            </tr>

            @foreach (var peak in Model.AthleteSummitCompletions)
            {
                <tr>
                    <td>
                        @Html.ActionLink(@peak.Peak.Name, "Details", "Peaks", new { id = @peak.Peak.Id }, null)
                    </td>
                    <td>
                        @((int)(peak.Peak.ELEV_METER * 3.28084)) ft
                    </td>
                    <td>
                        date
                    </td>
                    <td>
                        <a href="http://strava.com/activities/@peak.StravaActivityId">Activity</a>
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="col-lg-7">
        <div id='map'></div>
    </div>

    <script>

        mapboxgl.accessToken = 'pk.eyJ1IjoiZ2tyYXRod29obCIsImEiOiJ5bXlHNXJJIn0.gjNMPWKFNso_Z5EmEjsFGA';

        var featureList = [];

        $(document).ready(function () {
            var actionUrl = '@Url.Action("GetAthleteSummits", "Athletes", new { id=Model.AthleteId })';
            $.getJSON(actionUrl, displayData);
        });

        function displayData(response) {
            if (response != null) {
                console.log(response);
            }

            $.each(response, function (i, summit) {
                featureList.push({
                    "type": "Feature",
                    "properties": {
                        "description": "<div class=\"marker-title\">" + summit.Peak.Name + "</div><p>Elevation: " + (summit.Peak.ELEV_METER * 3.28084).toFixed(0) + "ft </p><p><a href=\"http://strava.com/activities/" + summit.StravaActivityId + "\" target=\"_blank\" title=\"Opens in a new window\">View on Strava</a></p>",
                        "marker-symbol": "mountain",
                        "icon-color": "#FF5900"
                    },
                    "geometry": {
                        "type": "Point",
                        "coordinates": [summit.Peak.Longitude.toFixed(4), summit.Peak.Latitude.toFixed(4)]
                    }
                });
            });



            var markers = {
                "type": "FeatureCollection",
                "features": featureList
            };

            var map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/mapbox/streets-v8',
                center: [-77.007481, 38.896516],
                zoom: 11.15
            });

            map.on('load', function () {
                // Add marker data as a new GeoJSON source.
                map.addSource("markers", {
                    "type": "geojson",
                    "data": markers
                });

                // Add a layer showing the markers.
                map.addLayer({
                    "id": "markers",
                    "type": "symbol",
                    "source": "markers",
                    "layout": {
                        "icon-image": "{marker-symbol}-15",
                        "icon-allow-overlap": true
                    }
                });

                // fit to bounds
                var bounds = new mapboxgl.LngLatBounds();
                markers.features.forEach(function (feature) {
                    bounds.extend(feature.geometry.coordinates);
                });
                map.fitBounds(bounds);

            });


        // When a click event occurs near a marker icon, open a popup at the location of
        // the feature, with description HTML from its properties.
            map.on('click', function (e) {
                var features = map.queryRenderedFeatures(e.point, { layers: ['markers'] });

                if (!features.length) {
                    return;
                }

                var feature = features[0];

                map.flyTo({ center: feature.geometry.coordinates });

                // Populate the popup and set its coordinates
                // based on the feature found.
                var popup = new mapboxgl.Popup()
                    .setLngLat(feature.geometry.coordinates)
                    .setHTML(feature.properties.description)
                    .addTo(map);
            });

            map.on('mousemove', function (e) {
                var features = map.queryRenderedFeatures(e.point, { layers: ['markers'] });
                map.getCanvas().style.cursor = (features.length) ? 'pointer' : '';
            });
        }

    </script>

</body>
</html>